version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: ot-postgres

    restart: always

    environment:
      POSTGRES_USER: otadmin
      POSTGRES_PASSWORD: otpassword
      POSTGRES_DB: otplatform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
